In [1]:
import numpy as np
import pandas as pd
import requests
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
data_alcohol = pd.read_csv("Data/russia_alcohol.csv")
data_demography = pd.read_csv("Data/russian_demography.csv")

In [6]:
data = data_demography.merge(data_alcohol)
data

,year,region,npg,birth_rate,death_rate,gdw,urbanization,wine,beer,vodka,champagne,brandy
0,1998,Republic of Adygea,-4.3,9.6,13.9,83.33,53.05,1.9,8.8,3.4,0.3,0.1
1,1998,Altai Krai,-4.0,8.8,12.8,72.67,52.76,3.3,19.2,11.3,1.1,0.1
2,1998,Amur Oblast,-1.8,10.4,12.2,65.59,66.07,2.1,21.2,17.3,0.7,0.4
3,1998,Arkhangelsk Oblast,-4.2,9.1,13.3,68.28,74.30,4.3,10.6,11.7,0.4,0.3
4,1998,Astrakhan Oblast,-3.7,9.6,13.3,73.76,68.13,2.9,18.0,9.5,0.8,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...
1610,2016,Chuvash Republic,0.0,13.2,13.2,74.05,61.30,5.0,42.3,7.7,0.7,0.4
1611,2016,Chukotka Autonomous Okrug,3.6,13.6,10.0,56.18,69.20,3.9,34.0,11.6,1.8,1.1
1612,2016,Sakha (Yakutia) Republic,7.6,16.0,8.4,67.83,65.40,4.3,56.1,8.2,1.8,0.5
1613,2016,Yamalo-Nenets Autonomous Okrug,10.1,15.4,5.3,51.10,83.70,4.5,75.8,8.2,1.7,1.3
1614,2016,Yaroslavl Oblast,-3.6,12.1,15.7,80.23,81.70,10.2,38.0,8.9,1.4,1.0

In [9]:
(data.isna().sum()/data.__len__())*100

year            0.000000
region          0.000000
npg             2.291022
birth_rate      2.291022
death_rate      2.414861
gdw             2.105263
urbanization    2.105263
wine            3.900929
beer            3.591331
vodka           3.777090
champagne       3.900929
brandy          4.086687
dtype: float64

In [21]:
total_alcohol_column = data["wine"] + data["beer"] + data["vodka"] + data["champagne"] + data["brandy"]

data["total_alcohol"] = total_alcohol_column
data

,year,region,npg,birth_rate,death_rate,gdw,urbanization,wine,beer,vodka,champagne,brandy,sum_alcohol,total_alcohol
0,1998,Republic of Adygea,-4.3,9.6,13.9,83.33,53.05,1.9,8.8,3.4,0.3,0.1,14.5,14.5
1,1998,Altai Krai,-4.0,8.8,12.8,72.67,52.76,3.3,19.2,11.3,1.1,0.1,35.0,35.0
2,1998,Amur Oblast,-1.8,10.4,12.2,65.59,66.07,2.1,21.2,17.3,0.7,0.4,41.7,41.7
3,1998,Arkhangelsk Oblast,-4.2,9.1,13.3,68.28,74.30,4.3,10.6,11.7,0.4,0.3,27.3,27.3
4,1998,Astrakhan Oblast,-3.7,9.6,13.3,73.76,68.13,2.9,18.0,9.5,0.8,0.2,31.4,31.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1610,2016,Chuvash Republic,0.0,13.2,13.2,74.05,61.30,5.0,42.3,7.7,0.7,0.4,56.1,56.1
1611,2016,Chukotka Autonomous Okrug,3.6,13.6,10.0,56.18,69.20,3.9,34.0,11.6,1.8,1.1,52.4,52.4
1612,2016,Sakha (Yakutia) Republic,7.6,16.0,8.4,67.83,65.40,4.3,56.1,8.2,1.8,0.5,70.9,70.9
1613,2016,Yamalo-Nenets Autonomous Okrug,10.1,15.4,5.3,51.10,83.70,4.5,75.8,8.2,1.7,1.3,91.5,91.5
1614,2016,Yaroslavl Oblast,-3.6,12.1,15.7,80.23,81.70,10.2,38.0,8.9,1.4,1.0,59.5,59.5

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1615 entries, 0 to 1614
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           1615 non-null   int64
 1   region         1615 non-null   object
 2   npg            1578 non-null   float64
 3   birth_rate     1578 non-null   float64
 4   death_rate     1576 non-null   float64
 5   gdw            1581 non-null   float64
 6   urbanization   1581 non-null   float64
 7   wine           1552 non-null   float64
 8   beer           1557 non-null   float64
 9   vodka          1554 non-null   float64
 10  champagne      1552 non-null   float64
 11  brandy         1549 non-null   float64
 12  sum_alcohol    1549 non-null   float64
 13  total_alcohol  1549 non-null   float64
dtypes: float64(12), int64(1), object(1)
memory usage: 189.3+ KB

In [23]:
data["region"].value_counts()

Republic of Adygea            19
Komi Republic                 19
Sverdlovsk Oblast             19
Sakhalin Oblast               19
Saratov Oblast                19
                              ..
Kirov Oblast                  19
Kemerovo Oblast               19
Republic of Karelia           19
Karachay-Cherkess Republic    19
Yaroslavl Oblast              19
Name: region, Length: 85, dtype: int64